import pytest

from custom_exceptions import UnboundedProbError

def test_unboundedproberror():
    return